name: toxicc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=1.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.5.1
  - nltk=3.5
  - notebook=6.3.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - regex=2021.3.17
  - requests=2.25.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.2
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wordcloud=1.8.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1

